### ISSUE TITLE
Issue converting detections to world (only in some cases)

### ISSUE THREAD

**Issue by mihsamusev** [ahrnbom/strudl#17]
Hi,
I'm on CUDA10 container. Performed all tasks until /jobs/detections_to_world_coordinates/post according to intended workflow.

After successfully converting 2 out of 8 videos i'm getting this error: 

```
Command: ['python', 'detections_world.py', '--cmd=findvids', '--dataset=thermal_20191204_17', '--run=run3', '--make_videos=False', '--ssdres=(320, 240, 3)', '--vidres=(640, 480, 3)', '--kltres=(320, 240)']
2020-04-06 13:02:17
20191204_162144_9UCI
Converting point tracks...
Converting to world coordinates...
20191204_162646_UREP
Converting point tracks...
Converting to world coordinates...
20191204_163146_XUT7
Converting point tracks...
Converting to world coordinates...
Traceback (most recent call last):
  File "detections_world.py", line 258, in <module>
    main()
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "detections_world.py", line 244, in main
    class_heights=class_heights)
  File "detections_world.py", line 111, in detections_to_3D
    klts_frame = pts.get_klts(fn, det)
  File "detections_world.py", line 60, in get_klts
    frame_indices = self.klt_frames[frame_number]
KeyError: 152
```
Detections in pixel coordinates and point tracks for all 8 videos look visually similar, by which i mean, all have some detections and some detected keypoints to track.

Do you know whats the reason for this error?
thanks

**Comment by ahrnbom** [comment]
It seems like point tracks haven't been computed for frame 152 for video 20191204_163146_XUT7. Could it be that the computation of point tracks were somehow cancelled in the middle of this video? Have you tried recomputing the point tracks?
